### PR TITLE
Use correct capitalization so go test works out of the box

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
Thanks, does Go complain about the folder name? I don't have any problem here

**Comment by Manishearth** [comment]
It's probably because you ran `go get github.com/gianlucaguarini/go-observable`

However, that's not the actual URL, and if you run `go get github.com/GianlucaGuarini/go-observable` then `go test` will not work

**Comment by GianlucaGuarini** [comment]
Ok I got it I will fix it also in the readme file, thank you

**Comment by Manishearth** [comment]
Additionally, you should make it thread safe. Either with a global lock that's used in a way so as to not cause any deadlocks, or with a per-callback-array lock and a global rwmutex that is write locked only on map insertion. Currently you're concurrently accessing a map of arrays and modifying both, this can cause data races.

**Comment by GianlucaGuarini** [comment]
@Manishearth good idea I can use rwmutex to lock the maps while they are processing the callbacks. Do you know how can I emulate a deadlocks testcase?

**Comment by Manishearth** [comment]
Basically, as long as no code reentrantly causes a lock it's fine. You shouldn't have code that calls a callback directly (spawning a goroutine is fine) between a lock and unlock.

**Comment by GianlucaGuarini** [comment]
@Manishearth if I run `go test -race` It fails also using `sync.Mutex` to spawn the go routines do you have any other hint?

**Comment by Manishearth** [comment]
Note that your tests themselves are racy too, since they're incrementing the same counter from multiple threads and stuff. Use a mutex in the tests whenever accessing the same variable from multiple callbacks.

**Pull request merged**
