### PR TITLE
Fix race condition when using goroutines (+ some maintenance)

### LINKED ISSUE #4: concurrent map read and map write
some times,it will throw "error:concurrent map read and map write" in golang 1.9

### PR DESCRIPTION
**Pull request by Geod24**
```
It is not uncommon to want one goroutine to turn some events `On`/`Off`
and to trigger those events, regardless of their current status,
from another goroutine.
This triggered the race detector, as synchronization for the map read/writes
was incomplete.
This adds a test which would fail before this changeset, and the fix to it.
```

I believe this fixes #4 (CC @lockp111)
To run the test case:
```console
% git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
% git checkout fix-race -- observable_test.go # Provided you have the branch locally
% go test ./... -race -timeout=2m
==================
WARNING: DATA RACE
Write at 0x00c0000967e0 by goroutine 23:
  runtime.mapassign_faststr()
      /usr/local/Cellar/go/1.11/libexec/src/runtime/map_faststr.go:190 +0x0
  github.com/GianlucaGuarini/go-observable.(*Observable).addCallback()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/helpers.go:21 +0x492
  github.com/GianlucaGuarini/go-observable.(*Observable).On()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/observable.go:39 +0x65
  github.com/GianlucaGuarini/go-observable_test.TestOnOffTriggerConcurrency.func2()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/observable_test.go:264 +0x8a

Previous read at 0x00c0000967e0 by goroutine 22:
  runtime.mapaccess2_faststr()
      /usr/local/Cellar/go/1.11/libexec/src/runtime/map_faststr.go:101 +0x0
  github.com/GianlucaGuarini/go-observable.(*Observable).Trigger()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/helpers.go:101 +0x249
  github.com/GianlucaGuarini/go-observable_test.TestOnOffTriggerConcurrency()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/observable_test.go:274 +0x1c4
  testing.tRunner()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0x162

Goroutine 23 (running) created at:
  github.com/GianlucaGuarini/go-observable_test.TestOnOffTriggerConcurrency()
      /Users/geod24/go/src/github.com/GianlucaGuarini/go-observable/observable_test.go:261 +0x13b
  testing.tRunner()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0x162

Goroutine 22 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:878 +0x650
  testing.runTests.func1()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0x162
  testing.runTests()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:66 +0x221
==================
--- FAIL: TestOnOffTriggerConcurrency (43.16s)
    testing.go:771: race detected during execution of test
FAIL
FAIL	github.com/GianlucaGuarini/go-observable	43.173s
```

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
Thanks for your pull request. Could you please avoid to change the files indentation in all the files? 
In that way I will be able then to check only the code you have updated

**Comment by Geod24** [comment]
@GianlucaGuarini : You can review commit by commit or ignore whitespace changes.
Regardless, I removed the `gofmt` commit.

**Comment by GianlucaGuarini** [comment]
thank you for your patch and your improvements

**Comment by GianlucaGuarini** [comment]
I am afraid that this patch doesn't solve the issue. The unit test fails on my machine :(:
```
==================
WARNING: DATA RACE
Write at 0x00c4200a67b0 by goroutine 22:
  runtime.mapassign_faststr()
      /usr/local/opt/go/libexec/src/runtime/hashmap_fast.go:694 +0x0
  /go-observable.(*Observable).addCallback()
      /go-observable/helpers.go:24 +0x32d
  /go-observable.(*Observable).On()
      /go-observable/observable.go:39 +0x65
  /go-observable_test.TestOnOffTriggerConcurrency.func2()
      /go-observable/observable_test.go:264 +0x8a

Previous read at 0x00c4200a67b0 by goroutine 21:
  runtime.mapaccess2_faststr()
      /usr/local/opt/go/libexec/src/runtime/hashmap_fast.go:261 +0x0
  /go-observable.(*Observable).Trigger()
      /go-observable/helpers.go:101 +0x246
  /go-observable_test.TestOnOffTriggerConcurrency()
      /go-observable/observable_test.go:274 +0x1c6
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:777 +0x16d

Goroutine 22 (running) created at:
  /go-observable_test.TestOnOffTriggerConcurrency()
      go-observable/observable_test.go:261 +0x13d
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:777 +0x16d

Goroutine 21 (running) created at:
  testing.(*T).Run()
      /usr/local/opt/go/libexec/src/testing/testing.go:824 +0x564
  testing.runTests.func1()
      /usr/local/opt/go/libexec/src/testing/testing.go:1063 +0xa4
  testing.tRunner()
      /usr/local/opt/go/libexec/src/testing/testing.go:777 +0x16d
  testing.runTests()
      /usr/local/opt/go/libexec/src/testing/testing.go:1061 +0x4e1
  testing.(*M).Run()
      /usr/local/opt/go/libexec/src/testing/testing.go:978 +0x2cd
  main.main()
      _testmain.go:66 +0x22a
==================
--- FAIL: TestOnOffTriggerConcurrency (46.70s)
  testing.go:730: race detected during execution of test
FAIL
FAIL  /go-observable 46.719s
```
I think that this issue could be solved only by using an asynchronous events queue

**Comment by Geod24** [comment]
Weird, it definitely pass on mine (OSX) and on Travis. What OS do you run ?
I ran `git remote update -p; git checkout upstream/dev; GOCACHE=off go test -a ./... -race` and everything seems fine.

An async event queue would be sweet, though.

**Pull request merged**
